# agent/research_agent.py
from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_classic.agents import create_tool_calling_agent, AgentExecutor
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from dotenv import load_dotenv
import os
from datetime import datetime
from docx import Document
from docx.shared import Inches

load_dotenv()

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.2,
)

search_tool = TavilySearchResults(max_results=6, search_depth="advanced")
tools = [search_tool]

prompt = ChatPromptTemplate.from_messages([
    ("system", """You are an expert Research Agent.
    Be thorough, accurate, objective, and well-structured.
    Always respond with these sections in your final answer:
    - Executive Summary
    - Key Findings
    - Detailed Analysis
    - Sources"""),
    MessagesPlaceholder(variable_name="chat_history", optional=True),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])

agent = create_tool_calling_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, handle_parsing_errors=True)


def save_to_word(content: str, query: str, version: int = 1) -> str:
    """Save research as Word document"""
    doc = Document()
    
    doc.add_heading(f"Research Report: {query}", level=0)
    doc.add_paragraph(f"Generated on: {datetime.now().strftime('%d %B %Y at %I:%M %p')}")
    doc.add_paragraph(f"Version: v{version}")
    doc.add_paragraph("-" * 70)

    doc.add_heading("Research Output", level=1)

    paragraphs = content.split('\n\n')
    for para in paragraphs:
        if para.strip():
            doc.add_paragraph(para.strip())

    doc.add_page_break()
    doc.add_paragraph("Generated by Research Agent (LangChain + Groq + Tavily)", style='Intense Quote')

    os.makedirs("research_reports", exist_ok=True)
    
    safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in query[:60])
    filename = f"research_reports/{safe_name}_v{version}_{datetime.now().strftime('%Y%m%d_%H%M')}.docx"
    
    doc.save(filename)
    print(f"\n Report saved: {filename}")
    return filename


def research(query: str):
    print(f"\n Researching: {query}\n")
    
    result = agent_executor.invoke({"input": query})
    final_output = result["output"]
    
    print("\n" + "="*80)
    print("FINAL RESEARCH OUTPUT")
    print("="*80)
    print(final_output)

    
    current_version = 1
    filename = save_to_word(final_output, query, current_version)

    while True:
        print("\n" + "-"*60)
        user_input = input("\nDo you need any changes to this research report? (yes/no): ").strip().lower()

        if user_input in ['no', 'n', 'exit', 'quit']:
            print(" Research completed. Thank you!")
            break

        if user_input in ['yes', 'y']:
            change_request = input("\nWhat changes would you like to make?\n> ").strip()
            
            if not change_request:
                print("No changes specified.")
                continue

            print("\n🔄 Revising report based on your feedback...")
            
            revision_prompt = f"""
            Here is the original research report:

            {final_output}

            The user wants the following changes:
            {change_request}

            Please revise the entire report accordingly. Keep the same structure:
            - Executive Summary
            - Key Findings  
            - Detailed Analysis
            - Sources

            Return only the full revised report.
            """
            revised_result = llm.invoke(revision_prompt)
            final_output = revised_result.content  

            current_version += 1
            filename = save_to_word(final_output, query, current_version)

            print(f"\n Revised version v{current_version} saved!")
        else:
            print("Please answer with 'yes' or 'no'.")
    
    print(f"\n🎉 Final report is ready: {filename}")